# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sohan/projects/OpenCV

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sohan/projects/OpenCV

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sohan/projects/OpenCV/CMakeFiles /home/sohan/projects/OpenCV/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sohan/projects/OpenCV/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named obj_detect

# Build rule for target.
obj_detect: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obj_detect
.PHONY : obj_detect

# fast build rule for target.
obj_detect/fast:
	$(MAKE) -f CMakeFiles/obj_detect.dir/build.make CMakeFiles/obj_detect.dir/build
.PHONY : obj_detect/fast

#=============================================================================
# Target rules for targets named task_dijkstra

# Build rule for target.
task_dijkstra: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 task_dijkstra
.PHONY : task_dijkstra

# fast build rule for target.
task_dijkstra/fast:
	$(MAKE) -f CMakeFiles/task_dijkstra.dir/build.make CMakeFiles/task_dijkstra.dir/build
.PHONY : task_dijkstra/fast

#=============================================================================
# Target rules for targets named canny

# Build rule for target.
canny: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 canny
.PHONY : canny

# fast build rule for target.
canny/fast:
	$(MAKE) -f CMakeFiles/canny.dir/build.make CMakeFiles/canny.dir/build
.PHONY : canny/fast

#=============================================================================
# Target rules for targets named video

# Build rule for target.
video: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 video
.PHONY : video

# fast build rule for target.
video/fast:
	$(MAKE) -f CMakeFiles/video.dir/build.make CMakeFiles/video.dir/build
.PHONY : video/fast

#=============================================================================
# Target rules for targets named tlr

# Build rule for target.
tlr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tlr
.PHONY : tlr

# fast build rule for target.
tlr/fast:
	$(MAKE) -f CMakeFiles/tlr.dir/build.make CMakeFiles/tlr.dir/build
.PHONY : tlr/fast

#=============================================================================
# Target rules for targets named task_Astar

# Build rule for target.
task_Astar: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 task_Astar
.PHONY : task_Astar

# fast build rule for target.
task_Astar/fast:
	$(MAKE) -f CMakeFiles/task_Astar.dir/build.make CMakeFiles/task_Astar.dir/build
.PHONY : task_Astar/fast

canny.o: canny.cpp.o

.PHONY : canny.o

# target to build an object file
canny.cpp.o:
	$(MAKE) -f CMakeFiles/canny.dir/build.make CMakeFiles/canny.dir/canny.cpp.o
.PHONY : canny.cpp.o

canny.i: canny.cpp.i

.PHONY : canny.i

# target to preprocess a source file
canny.cpp.i:
	$(MAKE) -f CMakeFiles/canny.dir/build.make CMakeFiles/canny.dir/canny.cpp.i
.PHONY : canny.cpp.i

canny.s: canny.cpp.s

.PHONY : canny.s

# target to generate assembly for a file
canny.cpp.s:
	$(MAKE) -f CMakeFiles/canny.dir/build.make CMakeFiles/canny.dir/canny.cpp.s
.PHONY : canny.cpp.s

obj_detect.o: obj_detect.cpp.o

.PHONY : obj_detect.o

# target to build an object file
obj_detect.cpp.o:
	$(MAKE) -f CMakeFiles/obj_detect.dir/build.make CMakeFiles/obj_detect.dir/obj_detect.cpp.o
.PHONY : obj_detect.cpp.o

obj_detect.i: obj_detect.cpp.i

.PHONY : obj_detect.i

# target to preprocess a source file
obj_detect.cpp.i:
	$(MAKE) -f CMakeFiles/obj_detect.dir/build.make CMakeFiles/obj_detect.dir/obj_detect.cpp.i
.PHONY : obj_detect.cpp.i

obj_detect.s: obj_detect.cpp.s

.PHONY : obj_detect.s

# target to generate assembly for a file
obj_detect.cpp.s:
	$(MAKE) -f CMakeFiles/obj_detect.dir/build.make CMakeFiles/obj_detect.dir/obj_detect.cpp.s
.PHONY : obj_detect.cpp.s

task_Astar.o: task_Astar.cpp.o

.PHONY : task_Astar.o

# target to build an object file
task_Astar.cpp.o:
	$(MAKE) -f CMakeFiles/task_Astar.dir/build.make CMakeFiles/task_Astar.dir/task_Astar.cpp.o
.PHONY : task_Astar.cpp.o

task_Astar.i: task_Astar.cpp.i

.PHONY : task_Astar.i

# target to preprocess a source file
task_Astar.cpp.i:
	$(MAKE) -f CMakeFiles/task_Astar.dir/build.make CMakeFiles/task_Astar.dir/task_Astar.cpp.i
.PHONY : task_Astar.cpp.i

task_Astar.s: task_Astar.cpp.s

.PHONY : task_Astar.s

# target to generate assembly for a file
task_Astar.cpp.s:
	$(MAKE) -f CMakeFiles/task_Astar.dir/build.make CMakeFiles/task_Astar.dir/task_Astar.cpp.s
.PHONY : task_Astar.cpp.s

task_dijkstra.o: task_dijkstra.cpp.o

.PHONY : task_dijkstra.o

# target to build an object file
task_dijkstra.cpp.o:
	$(MAKE) -f CMakeFiles/task_dijkstra.dir/build.make CMakeFiles/task_dijkstra.dir/task_dijkstra.cpp.o
.PHONY : task_dijkstra.cpp.o

task_dijkstra.i: task_dijkstra.cpp.i

.PHONY : task_dijkstra.i

# target to preprocess a source file
task_dijkstra.cpp.i:
	$(MAKE) -f CMakeFiles/task_dijkstra.dir/build.make CMakeFiles/task_dijkstra.dir/task_dijkstra.cpp.i
.PHONY : task_dijkstra.cpp.i

task_dijkstra.s: task_dijkstra.cpp.s

.PHONY : task_dijkstra.s

# target to generate assembly for a file
task_dijkstra.cpp.s:
	$(MAKE) -f CMakeFiles/task_dijkstra.dir/build.make CMakeFiles/task_dijkstra.dir/task_dijkstra.cpp.s
.PHONY : task_dijkstra.cpp.s

tlr.o: tlr.cpp.o

.PHONY : tlr.o

# target to build an object file
tlr.cpp.o:
	$(MAKE) -f CMakeFiles/tlr.dir/build.make CMakeFiles/tlr.dir/tlr.cpp.o
.PHONY : tlr.cpp.o

tlr.i: tlr.cpp.i

.PHONY : tlr.i

# target to preprocess a source file
tlr.cpp.i:
	$(MAKE) -f CMakeFiles/tlr.dir/build.make CMakeFiles/tlr.dir/tlr.cpp.i
.PHONY : tlr.cpp.i

tlr.s: tlr.cpp.s

.PHONY : tlr.s

# target to generate assembly for a file
tlr.cpp.s:
	$(MAKE) -f CMakeFiles/tlr.dir/build.make CMakeFiles/tlr.dir/tlr.cpp.s
.PHONY : tlr.cpp.s

video.o: video.cpp.o

.PHONY : video.o

# target to build an object file
video.cpp.o:
	$(MAKE) -f CMakeFiles/video.dir/build.make CMakeFiles/video.dir/video.cpp.o
.PHONY : video.cpp.o

video.i: video.cpp.i

.PHONY : video.i

# target to preprocess a source file
video.cpp.i:
	$(MAKE) -f CMakeFiles/video.dir/build.make CMakeFiles/video.dir/video.cpp.i
.PHONY : video.cpp.i

video.s: video.cpp.s

.PHONY : video.s

# target to generate assembly for a file
video.cpp.s:
	$(MAKE) -f CMakeFiles/video.dir/build.make CMakeFiles/video.dir/video.cpp.s
.PHONY : video.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... obj_detect"
	@echo "... task_dijkstra"
	@echo "... rebuild_cache"
	@echo "... canny"
	@echo "... video"
	@echo "... tlr"
	@echo "... task_Astar"
	@echo "... canny.o"
	@echo "... canny.i"
	@echo "... canny.s"
	@echo "... obj_detect.o"
	@echo "... obj_detect.i"
	@echo "... obj_detect.s"
	@echo "... task_Astar.o"
	@echo "... task_Astar.i"
	@echo "... task_Astar.s"
	@echo "... task_dijkstra.o"
	@echo "... task_dijkstra.i"
	@echo "... task_dijkstra.s"
	@echo "... tlr.o"
	@echo "... tlr.i"
	@echo "... tlr.s"
	@echo "... video.o"
	@echo "... video.i"
	@echo "... video.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

