# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sohan/projects/OpenCV

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sohan/projects/OpenCV

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sohan/projects/OpenCV/CMakeFiles /home/sohan/projects/OpenCV/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sohan/projects/OpenCV/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named video

# Build rule for target.
video: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 video
.PHONY : video

# fast build rule for target.
video/fast:
	$(MAKE) -f CMakeFiles/video.dir/build.make CMakeFiles/video.dir/build
.PHONY : video/fast

#=============================================================================
# Target rules for targets named canny

# Build rule for target.
canny: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 canny
.PHONY : canny

# fast build rule for target.
canny/fast:
	$(MAKE) -f CMakeFiles/canny.dir/build.make CMakeFiles/canny.dir/build
.PHONY : canny/fast

#=============================================================================
# Target rules for targets named watershed

# Build rule for target.
watershed: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 watershed
.PHONY : watershed

# fast build rule for target.
watershed/fast:
	$(MAKE) -f CMakeFiles/watershed.dir/build.make CMakeFiles/watershed.dir/build
.PHONY : watershed/fast

#=============================================================================
# Target rules for targets named convex_hull

# Build rule for target.
convex_hull: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 convex_hull
.PHONY : convex_hull

# fast build rule for target.
convex_hull/fast:
	$(MAKE) -f CMakeFiles/convex_hull.dir/build.make CMakeFiles/convex_hull.dir/build
.PHONY : convex_hull/fast

canny.o: canny.cpp.o

.PHONY : canny.o

# target to build an object file
canny.cpp.o:
	$(MAKE) -f CMakeFiles/canny.dir/build.make CMakeFiles/canny.dir/canny.cpp.o
.PHONY : canny.cpp.o

canny.i: canny.cpp.i

.PHONY : canny.i

# target to preprocess a source file
canny.cpp.i:
	$(MAKE) -f CMakeFiles/canny.dir/build.make CMakeFiles/canny.dir/canny.cpp.i
.PHONY : canny.cpp.i

canny.s: canny.cpp.s

.PHONY : canny.s

# target to generate assembly for a file
canny.cpp.s:
	$(MAKE) -f CMakeFiles/canny.dir/build.make CMakeFiles/canny.dir/canny.cpp.s
.PHONY : canny.cpp.s

convex_hull.o: convex_hull.cpp.o

.PHONY : convex_hull.o

# target to build an object file
convex_hull.cpp.o:
	$(MAKE) -f CMakeFiles/convex_hull.dir/build.make CMakeFiles/convex_hull.dir/convex_hull.cpp.o
.PHONY : convex_hull.cpp.o

convex_hull.i: convex_hull.cpp.i

.PHONY : convex_hull.i

# target to preprocess a source file
convex_hull.cpp.i:
	$(MAKE) -f CMakeFiles/convex_hull.dir/build.make CMakeFiles/convex_hull.dir/convex_hull.cpp.i
.PHONY : convex_hull.cpp.i

convex_hull.s: convex_hull.cpp.s

.PHONY : convex_hull.s

# target to generate assembly for a file
convex_hull.cpp.s:
	$(MAKE) -f CMakeFiles/convex_hull.dir/build.make CMakeFiles/convex_hull.dir/convex_hull.cpp.s
.PHONY : convex_hull.cpp.s

video.o: video.cpp.o

.PHONY : video.o

# target to build an object file
video.cpp.o:
	$(MAKE) -f CMakeFiles/video.dir/build.make CMakeFiles/video.dir/video.cpp.o
.PHONY : video.cpp.o

video.i: video.cpp.i

.PHONY : video.i

# target to preprocess a source file
video.cpp.i:
	$(MAKE) -f CMakeFiles/video.dir/build.make CMakeFiles/video.dir/video.cpp.i
.PHONY : video.cpp.i

video.s: video.cpp.s

.PHONY : video.s

# target to generate assembly for a file
video.cpp.s:
	$(MAKE) -f CMakeFiles/video.dir/build.make CMakeFiles/video.dir/video.cpp.s
.PHONY : video.cpp.s

watershed.o: watershed.cpp.o

.PHONY : watershed.o

# target to build an object file
watershed.cpp.o:
	$(MAKE) -f CMakeFiles/watershed.dir/build.make CMakeFiles/watershed.dir/watershed.cpp.o
.PHONY : watershed.cpp.o

watershed.i: watershed.cpp.i

.PHONY : watershed.i

# target to preprocess a source file
watershed.cpp.i:
	$(MAKE) -f CMakeFiles/watershed.dir/build.make CMakeFiles/watershed.dir/watershed.cpp.i
.PHONY : watershed.cpp.i

watershed.s: watershed.cpp.s

.PHONY : watershed.s

# target to generate assembly for a file
watershed.cpp.s:
	$(MAKE) -f CMakeFiles/watershed.dir/build.make CMakeFiles/watershed.dir/watershed.cpp.s
.PHONY : watershed.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... video"
	@echo "... rebuild_cache"
	@echo "... canny"
	@echo "... watershed"
	@echo "... convex_hull"
	@echo "... canny.o"
	@echo "... canny.i"
	@echo "... canny.s"
	@echo "... convex_hull.o"
	@echo "... convex_hull.i"
	@echo "... convex_hull.s"
	@echo "... video.o"
	@echo "... video.i"
	@echo "... video.s"
	@echo "... watershed.o"
	@echo "... watershed.i"
	@echo "... watershed.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

